# Generated by Django 4.1 on 2022-09-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_quantity_per_unit_ingredient_quantity_per_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='menu_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient_list',
            field=models.JSONField(default=dict),
        ),
    ]
