# Generated by Django 4.1 on 2022-09-06 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_menuitem_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='id',
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.menuitem'),
        ),
    ]
